### ISSUE TITLE
I'm not a zombie

### ISSUE THREAD

**Issue by ZenPylon** [ShanaScogin/QuantMethods#1]
Despite my best efforts, I am not a zombie.  I was wondering if your code could help with this.

Thanks.

**Comment by ShanaScogin** [comment]
Try stretching more and taking long walks in nature. Code alone cannot lead you to your true or untrue zombie self.

**Comment by ZenPylon** [comment]
Spoken like a true master.  Though I must say, code can be quite nice.  E.g. :

https://github.com/ShanaScogin/QuantMethods/commit/fdd6147d72bdeea74d2f55e2cb05a75d27e88d06
